export const PLANS = [
  {
    id: "1-month",
    name: "1 Month",
    duration: 30,
    price: 999,
    priceLabel: "₹999",
    period: "/month",
    description: "Perfect for quick interview preparation",
    popular: false,
    enterprise: false,
    features: {
      "Resume ATS Analysis": true,
      "Resume Based Questions": true,
      "HR Interview": true,
      "Technical Interview": true,
      "AI Evaluation": true,
      "Voice Analysis": true,
      "Video Analysis": false,
      "AI Reports": true,
      "Cross Questioning": false,
      "Adaptive Difficulty": false,
      "Multi Interview Panel": false,
      "Real Time AI Coach": false,
      "Interview Replay": false,
      "Placement Certificate": false,
      "AI Memory Engine": false,
      "Company Specific Interviews": false,
    },
    modules: ["AI Mock Interview", "Aptitude Assessment", "Coding Assessment"],
    interviewLevels: 1,
    storage: "5 GB",
    support: "Email Support",
    certificate: false,
    reports: "Basic Reports",
  },
  {
    id: "3-month",
    name: "3 Month",
    duration: 90,
    price: 2499,
    priceLabel: "₹2,499",
    period: "/quarter",
    description: "Best for semester exam preparation",
    popular: false,
    enterprise: false,
    features: {
      "Resume ATS Analysis": true,
      "Resume Based Questions": true,
      "HR Interview": true,
      "Technical Interview": true,
      "AI Evaluation": true,
      "Voice Analysis": true,
      "Video Analysis": true,
      "AI Reports": true,
      "Cross Questioning": true,
      "Adaptive Difficulty": false,
      "Multi Interview Panel": false,
      "Real Time AI Coach": false,
      "Interview Replay": false,
      "Placement Certificate": false,
      "AI Memory Engine": false,
      "Company Specific Interviews": false,
    },
    modules: ["AI Mock Interview", "Aptitude Assessment", "Coding Assessment", "Communication Evaluation"],
    interviewLevels: 2,
    storage: "25 GB",
    support: "Priority Email Support",
    certificate: false,
    reports: "Advanced Reports",
  },
  {
    id: "6-month",
    name: "6 Month",
    duration: 180,
    price: 3999,
    priceLabel: "₹3,999",
    period: "/half-year",
    description: "Most popular for placement preparation",
    popular: true,
    enterprise: false,
    features: {
      "Resume ATS Analysis": true,
      "Resume Based Questions": true,
      "HR Interview": true,
      "Technical Interview": true,
      "AI Evaluation": true,
      "Voice Analysis": true,
      "Video Analysis": true,
      "AI Reports": true,
      "Cross Questioning": true,
      "Adaptive Difficulty": true,
      "Multi Interview Panel": true,
      "Real Time AI Coach": true,
      "Interview Replay": false,
      "Placement Certificate": true,
      "AI Memory Engine": false,
      "Company Specific Interviews": false,
    },
    modules: ["AI Mock Interview", "Aptitude Assessment", "Coding Assessment", "Communication Evaluation", "AI Resume Builder"],
    interviewLevels: 3,
    storage: "50 GB",
    support: "Chat Support",
    certificate: true,
    reports: "Comprehensive Reports",
  },
  {
    id: "1-year",
    name: "1 Year",
    duration: 365,
    price: 6999,
    priceLabel: "₹6,999",
    period: "/year",
    description: "Complete year-long placement preparation",
    popular: false,
    enterprise: true,
    features: {
      "Resume ATS Analysis": true,
      "Resume Based Questions": true,
      "HR Interview": true,
      "Technical Interview": true,
      "AI Evaluation": true,
      "Voice Analysis": true,
      "Video Analysis": true,
      "AI Reports": true,
      "Cross Questioning": true,
      "Adaptive Difficulty": true,
      "Multi Interview Panel": true,
      "Real Time AI Coach": true,
      "Interview Replay": true,
      "Placement Certificate": true,
      "AI Memory Engine": true,
      "Company Specific Interviews": true,
    },
    modules: ["All Modules"],
    interviewLevels: 4,
    storage: "100 GB",
    support: "24/7 Priority Support",
    certificate: true,
    reports: "Enterprise Reports & Analytics",
  },
]

export const FEATURES_LIST = [
  "Resume ATS Analysis",
  "Resume Based Questions",
  "HR Interview",
  "Technical Interview",
  "AI Evaluation",
  "Voice Analysis",
  "Video Analysis",
  "AI Reports",
  "Cross Questioning",
  "Adaptive Difficulty",
  "Multi Interview Panel",
  "Real Time AI Coach",
  "Interview Replay",
  "Placement Certificate",
  "AI Memory Engine",
  "Company Specific Interviews",
]

export const MODULES = [
  {
    id: "ai-mock-interview",
    title: "AI Mock Interview",
    description: "Practice with AI-powered interviews that simulate real company interviews with adaptive questioning and real-time feedback.",
    icon: "Brain",
    color: "#123D32",
    features: ["Real-time AI evaluation", "Voice and video analysis", "Company specific interviews", "Cross questioning"],
  },
  {
    id: "aptitude-assessment",
    title: "Aptitude Assessment",
    description: "Comprehensive aptitude tests covering quantitative, logical, and verbal reasoning with performance analytics.",
    icon: "BarChart3",
    color: "#2F7D5B",
    features: ["Quantitative reasoning", "Logical reasoning", "Verbal ability", "Performance analytics"],
  },
  {
    id: "coding-assessment",
    title: "Coding Assessment",
    description: "Practice coding problems with AI evaluation, multiple languages, and real-time code analysis.",
    icon: "Code2",
    color: "#123D32",
    features: ["Multiple languages", "AI code evaluation", "Real-time feedback", "Progress tracking"],
  },
  {
    id: "communication-evaluation",
    title: "Communication Evaluation",
    description: "Evaluate and improve communication skills with AI-powered speech analysis and feedback.",
    icon: "MessageSquare",
    color: "#2F7D5B",
    features: ["Speech analysis", "Fluency assessment", "Pronunciation scoring", "Confidence tracking"],
  },
  {
    id: "ai-resume-builder",
    title: "AI Resume Builder",
    description: "Build ATS-optimized resumes with AI suggestions, real-time formatting, and industry-specific templates.",
    icon: "FileText",
    color: "#123D32",
    features: ["ATS optimization", "AI suggestions", "Industry templates", "Formatting assistance"],
  },
]

export const INTERVIEW_LEVELS = [
  {
    level: 1,
    title: "Interview Foundation",
    subtitle: "Level 1",
    description: "Build your interview foundation with basic HR and technical question practice. Learn the fundamentals of interview etiquette and response structure.",
    duration: "0-30 days",
    features: ["Basic HR Interview Questions", "Common Technical Questions", "Resume Based Questions", "AI Evaluation"],
  },
  {
    level: 2,
    title: "Professional Growth",
    subtitle: "Level 2",
    description: "Advance your skills with role-specific questions, voice analysis, and comprehensive feedback loops.",
    duration: "30-90 days",
    features: ["Role Specific Questions", "Voice Analysis", "Video Analysis", "Cross Questioning", "Detailed AI Reports"],
  },
  {
    level: 3,
    title: "Placement Ready",
    subtitle: "Level 3",
    description: "Get placement ready with multi-panel interviews, adaptive difficulty, and real-time AI coaching.",
    duration: "90-180 days",
    features: ["Multi Interview Panel", "Adaptive Difficulty", "Real Time AI Coach", "Company Specific Questions", "Placement Certificate"],
  },
  {
    level: 4,
    title: "AI Mentorship",
    subtitle: "Level 4",
    description: "Enterprise-grade AI mentorship with memory engine, interview replay, and personalized career guidance.",
    duration: "180-365 days",
    features: ["AI Memory Engine", "Interview Replay", "Personalized Mentorship", "Career Guidance", "Company Specific Interviews"],
  },
]

export const DASHBOARDS = [
  {
    title: "Student Dashboard",
    description: "Track your interview performance, coding progress, aptitude scores, and overall placement readiness.",
    role: "Student",
  },
  {
    title: "Institution Dashboard",
    description: "Monitor institution-wide placement metrics, department performance, and student progress analytics.",
    role: "Institution",
  },
  {
    title: "Placement Officer Dashboard",
    description: "Manage placement drives, track student readiness, and generate placement reports.",
    role: "Placement Officer",
  },
  {
    title: "Faculty Dashboard",
    description: "View student performance, identify weak areas, and track department-wise progress.",
    role: "Faculty",
  },
]

export const BENEFITS = {
  students: [
    "AI-powered personalized interview practice",
    "Real-time feedback and improvement suggestions",
    "Track your placement readiness score",
    "Access to company-specific interview questions",
    "Build ATS-optimized resumes",
    "Certificate upon completion",
  ],
  faculty: [
    "Monitor student progress in real-time",
    "Identify weak areas across departments",
    "Generate comprehensive performance reports",
    "Track placement preparation metrics",
    "View detailed analytics and insights",
    "Save time with automated evaluation",
  ],
  institutions: [
    "Complete placement management platform",
    "Institution-wide analytics and reporting",
    "Track placement readiness across departments",
    "Automated placement drive management",
    "Generate institutional reports",
    "Improve placement statistics",
  ],
  placementOfficers: [
    "Manage multiple placement drives",
    "Track student readiness scores",
    "Generate placement reports instantly",
    "Communication with recruiters",
    "View department-wise analytics",
    "Monitor placement progress",
  ],
}

export const REPORTS = [
  { title: "Student Reports", description: "Individual student performance analysis", icon: "User" },
  { title: "Department Reports", description: "Department-wise progress and analytics", icon: "Building2" },
  { title: "Coding Reports", description: "Coding assessment performance metrics", icon: "Code2" },
  { title: "Communication Reports", description: "Communication skill evaluation results", icon: "MessageSquare" },
  { title: "Interview Reports", description: "Interview performance and improvement areas", icon: "Briefcase" },
  { title: "Placement Reports", description: "Placement readiness and statistics", icon: "Target" },
  { title: "Resume Reports", description: "Resume ATS score and suggestions", icon: "FileText" },
  { title: "Analytics", description: "Comprehensive platform analytics", icon: "BarChart3" },
]

export const FEATURES_LOCKED = {
  "1-month": {
    "Resume ATS Analysis": true,
    "Resume Based Questions": true,
    "HR Interview": true,
    "Technical Interview": true,
    "AI Evaluation": true,
    "Voice Analysis": true,
    "Video Analysis": false,
    "AI Reports": true,
    "Cross Questioning": false,
    "Adaptive Difficulty": false,
    "Multi Interview Panel": false,
    "Real Time AI Coach": false,
    "Interview Replay": false,
    "Placement Certificate": false,
    "AI Memory Engine": false,
    "Company Specific Interviews": false,
  },
  "3-month": {
    "Resume ATS Analysis": true,
    "Resume Based Questions": true,
    "HR Interview": true,
    "Technical Interview": true,
    "AI Evaluation": true,
    "Voice Analysis": true,
    "Video Analysis": true,
    "AI Reports": true,
    "Cross Questioning": true,
    "Adaptive Difficulty": false,
    "Multi Interview Panel": false,
    "Real Time AI Coach": false,
    "Interview Replay": false,
    "Placement Certificate": false,
    "AI Memory Engine": false,
    "Company Specific Interviews": false,
  },
  "6-month": {
    "Resume ATS Analysis": true,
    "Resume Based Questions": true,
    "HR Interview": true,
    "Technical Interview": true,
    "AI Evaluation": true,
    "Voice Analysis": true,
    "Video Analysis": true,
    "AI Reports": true,
    "Cross Questioning": true,
    "Adaptive Difficulty": true,
    "Multi Interview Panel": true,
    "Real Time AI Coach": true,
    "Interview Replay": false,
    "Placement Certificate": true,
    "AI Memory Engine": false,
    "Company Specific Interviews": false,
  },
  "1-year": {
    "Resume ATS Analysis": true,
    "Resume Based Questions": true,
    "HR Interview": true,
    "Technical Interview": true,
    "AI Evaluation": true,
    "Voice Analysis": true,
    "Video Analysis": true,
    "AI Reports": true,
    "Cross Questioning": true,
    "Adaptive Difficulty": true,
    "Multi Interview Panel": true,
    "Real Time AI Coach": true,
    "Interview Replay": true,
    "Placement Certificate": true,
    "AI Memory Engine": true,
    "Company Specific Interviews": true,
  },
}
